# Generated by Django 4.1.2 on 2022-11-14 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioprevisto',
            name='id_previsao',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='horarioreal',
            name='chegada_real',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='horarioreal',
            name='id_real',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='horarioreal',
            name='partida_real',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='id_relatorio',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rota',
            name='id_rota',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='id_status',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_voo',
            field=models.CharField(default='EMBARCANDO', max_length=20),
        ),
    ]
