# Generated by Django 4.1 on 2022-11-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0004_user_profession'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
