# Generated by Django 4.1.2 on 2022-11-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0005_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(choices=[('1', 'manager'), ('2', 'operator'), ('3', 'employee'), ('4', 'pilot'), ('5', 'unauthorized')], default=('4', 'pilot'), max_length=20),
        ),
    ]
