# Generated by Django 4.1 on 2022-11-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0006_alter_user_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_voo',
            field=models.CharField(default='CANCELADO', max_length=20),
        ),
    ]
