# Generated by Django 4.1 on 2022-11-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0007_alter_status_status_voo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='erro',
            field=models.IntegerField(null=True),
        ),
    ]
